authors:
  samuelrince:
    name: Samuel Rincé
    description: Founder & Maintainer
    avatar: https://avatars.githubusercontent.com/u/35747570
    url: https://github.com/samuelrince

  adrienbanse:
    name: Adrien Banse
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/45042779
    url: https://github.com/adrienbanse

  clairesaignol:
    name: Claire Saignol
    description: Partnerships Lead
    avatar: https://raw.githubusercontent.com/genai-impact/website/refs/heads/main/assets/images/people/claire_saignol.jpg
    url: https://www.linkedin.com/in/claire-saignol/
