authors:
  samuelrince:
    name: Samuel Rincé
    description: Founder & Maintainer
    avatar: https://avatars.githubusercontent.com/u/35747570
    url: https://github.com/samuelrince

  adrienbanse:
    name: Adrien Banse
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/45042779
    url: https://github.com/adrienbanse

  clairesaignol:
    name: Claire Saignol
    description: Head of Partnerships
    avatar: https://avatars.githubusercontent.com/u/280668843
    url: https://www.linkedin.com/in/claire-saignol/
